---
# tasks file for apache-webserver
- name: install apache on debian
  apt:
    name: "{{ apache_package_deb }}"
    state: present
  when: ansible_os_family == "Debian"
- name: install apache on apache_package_rhel
  yum:
    name: "{{ apache_package_rhel }}"
    state: present
  when: ansible_os_family = "RedHat"
- name: set service name for debian
  set_fact:
    apache_package: "{{ apache_package_deb }}"
  when: ansible_os_family == "Debian"
- name: set service name for Redhat
  set_fact:
    apache_package: "{{ apache_package_rhel }}"
  when: ansible_os_family == "Redhat"
- name: service enable and start
  service:
    name: "{{ apache_package}}"
    enable: yes
    state: started
- name: test by print
  debug:
    msg: firing nortification for redhat
  nortify: restart rhel apache
  when: ansible_os_family == "RedHat"

  